document.querySelectorAll('.total-count > span')[0].innerHTML = data_mod.length;
console.log(data_mod.length);
document.querySelectorAll('.more-count > span')[0].innerHTML = count_pos;
console.log(count_pos);
document.querySelectorAll('.less-count > span')[0].innerHTML = count_neg;
console.log(count_neg);
document.querySelectorAll('.equal-count > span')[0].innerHTML = count_zero;
console.log(count_zero);
document.querySelectorAll('.null-count > span')[0].innerHTML = count_null;
console.log(count_null);